// const FETCH_ITEMS_LOADING = "FETCH_ITEMS"
// const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS"
// const FETCH_ITEMS_ERROR = "FETCH_ITEMS_ERROR"

export const COUNTER_COUNT_UP = "COUNTER_COUNT_UP"
export const COUNTER_COUNT_DOWN = "COUNTER_COUNT_DOWN"
